[workspace]
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "pytorch-max-bridge"
# Add support for multiple platforms
# Slides work on Linux, Mac, and Windows but MAX/Mojo GPU requires Linux
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.0.0"

[feature.cuda]
platforms = ["linux-64"]
channels = ["nvidia"]
system-requirements = { cuda = "12" }

[feature.cuda.dependencies]
cuda-toolkit = "12.*"

[feature.cuda.pypi-dependencies]
torch = { version = "==2.7.1", index = "https://download.pytorch.org/whl/cu128" }

[feature.rocm]
platforms = ["linux-64"]

[feature.rocm.pypi-dependencies]
torch = { version = "==2.7.1", index = "https://download.pytorch.org/whl/rocm6.3" }
pytorch-triton-rocm = { index = "https://download.pytorch.org/whl/rocm6.3" }

[tasks]
slide-install = "npm install"
dev-slides = "npm run dev"
slides = "npm start"
pdf = "npm run pdf"

# Cross-platform dependencies
[dependencies]
nodejs = ">=22.13.0,<22.14"

[target.linux-64.dependencies]
python = ">=3.10,<3.13"
ipykernel = ">=6.29.5,<7"
max = "==25.5.0.dev2025071105"
matplotlib = ">=3.10.3,<4"
rich = ">=14.0.0,<15"
notebook = ">=7.4.4,<8"
ipywidgets = ">=8.1.7,<9"
jupyterlab = ">=4.4.4,<5"
scipy = ">=1.16.0,<2"

[target.linux-64.pypi-dependencies]
transformers = ">=4.53.2, <5"

[environments]
cuda = { features = ["cuda"], solve-group = "cuda" }
rocm = { features = ["rocm"], solve-group = "rocm" }
